"""Margin carry analysis engine.

Calculates income vs. margin cost for leveraged portfolios.
Surfaces factual carry metrics -- does not recommend actions.
"""

from __future__ import annotations

import math
from dataclasses import dataclass


@dataclass
class PositionCarry:
    """Carry metrics for a single position."""

    symbol: str
    market_value: float
    yield_pct: float
    annual_income: float
    margin_allocated: float
    margin_rate: float
    annual_margin_cost: float
    net_carry: float
    carry_spread: float


@dataclass
class PortfolioCarry:
    """Aggregate carry metrics for the entire portfolio."""

    total_nav: float
    total_long_value: float
    total_margin: float
    leverage_ratio: float
    total_annual_income: float
    total_annual_margin_cost: float
    net_carry: float
    income_coverage_ratio: float
    margin_as_pct_of_nav: float
    positions: list[PositionCarry]


class CarryError(Exception):
    """Raised when carry analysis encounters invalid inputs."""


def _validate_holdings(holdings: list[dict]) -> None:
    """Validate holdings input for carry analysis.

    Args:
        holdings: List of holding dicts with 'symbol' and 'market_value' keys.

    Raises:
        ValueError: If holdings are empty or contain invalid data.
    """
    if not holdings:
        msg = "Holdings list must not be empty"
        raise ValueError(msg)

    for i, h in enumerate(holdings):
        if "symbol" not in h or not str(h.get("symbol", "")).strip():
            msg = f"Holding at index {i} is missing a valid 'symbol'"
            raise ValueError(msg)

        if "market_value" not in h:
            msg = f"Holding '{h.get('symbol', i)}' is missing 'market_value'"
            raise ValueError(msg)

        mv = h["market_value"]
        if not isinstance(mv, (int, float)) or math.isnan(mv) or math.isinf(mv):
            msg = f"Holding '{h['symbol']}' has invalid market_value: {mv}"
            raise ValueError(msg)

        if mv < 0:
            msg = f"Holding '{h['symbol']}' has negative market_value: {mv}"
            raise ValueError(msg)

        yield_pct = h.get("yield_pct", 0.0)
        if isinstance(yield_pct, (int, float)) and (
            math.isnan(yield_pct) or math.isinf(yield_pct)
        ):
            msg = f"Holding '{h['symbol']}' has invalid yield_pct: {yield_pct}"
            raise ValueError(msg)


def _validate_margin_params(total_margin: float, margin_rate: float) -> None:
    """Validate margin parameters.

    Args:
        total_margin: Total margin borrowed.
        margin_rate: Annual margin interest rate (decimal).

    Raises:
        ValueError: If margin parameters are invalid.
    """
    if math.isnan(total_margin) or math.isinf(total_margin):
        msg = f"total_margin is invalid: {total_margin}"
        raise ValueError(msg)

    if total_margin < 0:
        msg = f"total_margin must not be negative: {total_margin}"
        raise ValueError(msg)

    if math.isnan(margin_rate) or math.isinf(margin_rate):
        msg = f"margin_rate is invalid: {margin_rate}"
        raise ValueError(msg)

    if margin_rate < 0:
        msg = f"margin_rate must not be negative: {margin_rate}"
        raise ValueError(msg)


def analyze_carry(
    holdings: list[dict],
    total_margin: float,
    margin_rate: float = 0.058,
) -> PortfolioCarry:
    """Compute carry analysis for a leveraged portfolio.

    Calculates the income generated by each position versus the margin cost
    allocated proportionally by market value. Surfaces net carry, coverage
    ratio, and leverage metrics.

    Args:
        holdings: List of holding dicts. Required keys: 'symbol', 'market_value'.
            Optional: 'yield_pct' (annual yield as percentage, e.g. 4.5 for 4.5%).
        total_margin: Total margin (borrowed amount) in the portfolio.
        margin_rate: Annual margin interest rate as a decimal (default: 0.058 = 5.8%).

    Returns:
        PortfolioCarry with per-position and aggregate carry metrics.

    Raises:
        ValueError: If holdings are empty, contain invalid values, or margin
            parameters are invalid (negative, NaN, Infinity).
    """
    _validate_holdings(holdings)
    _validate_margin_params(total_margin, margin_rate)

    total_long = sum(h["market_value"] for h in holdings)

    # NAV = total long value minus margin borrowed
    total_nav = total_long - total_margin

    positions: list[PositionCarry] = []
    total_income = 0.0

    for h in holdings:
        yield_pct = h.get("yield_pct", 0.0)
        if yield_pct is None:
            yield_pct = 0.0

        mv = h["market_value"]
        income = mv * (yield_pct / 100.0)
        total_income += income

        # Allocate margin proportionally by market value
        # Guard: if total_long is zero, no margin allocation
        margin_share = (mv / total_long * total_margin) if total_long > 0 else 0.0
        margin_cost = margin_share * margin_rate
        net = income - margin_cost

        # carry_spread: yield minus margin rate
        # Guard against division-related issues with yield_pct
        spread = yield_pct / 100.0 - margin_rate

        positions.append(PositionCarry(
            symbol=h["symbol"],
            market_value=mv,
            yield_pct=yield_pct,
            annual_income=round(income, 2),
            margin_allocated=round(margin_share, 2),
            margin_rate=margin_rate,
            annual_margin_cost=round(margin_cost, 2),
            net_carry=round(net, 2),
            carry_spread=round(spread, 4),
        ))

    total_margin_cost = total_margin * margin_rate
    net_carry = total_income - total_margin_cost

    # Income coverage ratio: how many times income covers margin cost
    # Guard: if margin cost is zero, coverage is infinite (no cost to cover)
    if total_margin_cost > 0:
        coverage = total_income / total_margin_cost
    else:
        coverage = float("inf") if total_income > 0 else 0.0

    # Leverage ratio: total long / NAV
    # Guard: if NAV is zero or negative, leverage is undefined
    leverage = total_long / total_nav if total_nav > 0 else 0.0

    # Margin as percentage of NAV
    # Guard: if NAV is zero or negative, return 0.0
    margin_pct = (
        round(total_margin / total_nav * 100, 1) if total_nav > 0 else 0.0
    )

    return PortfolioCarry(
        total_nav=round(total_nav, 2),
        total_long_value=round(total_long, 2),
        total_margin=round(total_margin, 2),
        leverage_ratio=round(leverage, 2),
        total_annual_income=round(total_income, 2),
        total_annual_margin_cost=round(total_margin_cost, 2),
        net_carry=round(net_carry, 2),
        income_coverage_ratio=round(coverage, 2),
        margin_as_pct_of_nav=margin_pct,
        positions=positions,
    )
